/* Static market data loader for SEO pages.
   Data is generated by scripts/generate_market_data.py at build time. */

export interface MunicipalityData {
  name: string;
  slug: string;
  code: string;
  population: number;
  households: number;
  subscribers: number;
  isp_count: number;
  penetration: number;
  hhi: number;
  hhi_class: 'competitivo' | 'moderado' | 'concentrado';
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  dsl_pct: number;
  fwa_pct: number;
  quality: { ouro: number; prata: number; bronze: number; sem_selo: number };
  teasers: { tax_debt_isps: number; complaints: number; ouro_isps: number };
  growth_pct: number;
}

export interface QuarterlyData {
  quarter: string;
  subscribers: number;
  fiber_pct: number;
  isp_count: number;
}

export interface TechSnapshot {
  period: string;
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  dsl_pct: number;
}

export interface ComplaintQuarter {
  quarter: string;
  count: number;
  avg_response_days: number | null;
  avg_satisfaction: number | null;
}

export interface EmploymentYear {
  year: number;
  telecom_jobs: number;
  avg_salary_brl: number | null;
}

export interface EconomyData {
  year: number;
  proxy_pib: number;
}

export interface StateInsights {
  narrative: string;
}

export interface StateSummary {
  uf: string;
  name: string;
  subscribers: number;
  municipalities: number;
  avg_hhi: number;
  avg_penetration: number;
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  quality: { ouro: number; prata: number; bronze: number; sem_selo: number };
  monopoly_count: number;
  coverage_gap_count: number;
}

export interface NationalData {
  subscribers: number;
  municipalities: number;
  states: StateSummary[];
  period: string;
  generated: string;
}

export interface StateData extends StateSummary {
  cities: MunicipalityData[];
  period: string;
  timeseries: QuarterlyData[];
  tech_evolution: { before?: TechSnapshot; after?: TechSnapshot };
  complaints: ComplaintQuarter[];
  employment: EmploymentYear[];
  economy: EconomyData | Record<string, never>;
  insights: StateInsights;
}

// Import JSON at build time (Next.js static import)
export function getNationalData(): NationalData {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  return require('@/data/market/index.json') as NationalData;
}

export function getStateData(uf: string): StateData | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(`@/data/market/states/${uf.toLowerCase()}.json`) as StateData;
  } catch {
    return null;
  }
}

export function getMunicipalityData(uf: string, slug: string): { state: StateData; city: MunicipalityData } | null {
  const state = getStateData(uf);
  if (!state) return null;
  const city = state.cities.find((c) => c.slug === slug);
  if (!city) return null;
  return { state, city };
}

export function getAllStateUFs(): string[] {
  const national = getNationalData();
  return national.states.map((s) => s.uf.toLowerCase());
}

export function getAllMunicipalitySlugs(): { uf: string; slug: string }[] {
  const national = getNationalData();
  const result: { uf: string; slug: string }[] = [];
  for (const st of national.states) {
    const state = getStateData(st.uf);
    if (state) {
      for (const city of state.cities) {
        result.push({ uf: st.uf.toLowerCase(), slug: city.slug });
      }
    }
  }
  return result;
}

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace('.0', '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1).replace('.0', '')}K`;
  return n.toLocaleString('pt-BR');
}

export function formatSubscribers(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace('.0', '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return n.toLocaleString('pt-BR');
}

const STATE_NAMES: Record<string, string> = {
  ac: 'Acre', al: 'Alagoas', ap: 'Amapá', am: 'Amazonas',
  ba: 'Bahia', ce: 'Ceará', df: 'Distrito Federal', es: 'Espírito Santo',
  go: 'Goiás', ma: 'Maranhão', mt: 'Mato Grosso', ms: 'Mato Grosso do Sul',
  mg: 'Minas Gerais', pa: 'Pará', pb: 'Paraíba', pr: 'Paraná',
  pe: 'Pernambuco', pi: 'Piauí', rj: 'Rio de Janeiro', rn: 'Rio Grande do Norte',
  rs: 'Rio Grande do Sul', ro: 'Rondônia', rr: 'Roraima', sc: 'Santa Catarina',
  sp: 'São Paulo', se: 'Sergipe', to: 'Tocantins',
};

export function getStateName(uf: string): string {
  return STATE_NAMES[uf.toLowerCase()] || uf.toUpperCase();
}
