/* Static market data loader for SEO pages.
   Data is generated by scripts/generate_market_data.py at build time. */

export interface OpportunityScore {
  level: 'alto' | 'moderado' | 'baixo' | 'muito_baixo';
  demand_level: 'alto' | 'moderado' | 'baixo';
  competition_level: 'alto' | 'moderado' | 'baixo';
  infrastructure_level: 'alto' | 'moderado' | 'baixo';
  growth_level: 'alto' | 'moderado' | 'baixo';
}

export interface SchoolData {
  total: number;
  no_internet: number;
  students: number;
}

export interface HealthData {
  facilities: number;
  beds: number;
}

export interface SafetyData {
  homicide_rate: number;
  risk_score: number;
}

export interface SanitationData {
  water_pct: number;
  sewage_pct: number;
  water_loss_pct: number;
}

export interface MuniEconomyData {
  pib_per_capita: number;
  formal_employment: number;
}

export interface DensityData {
  addresses: number;
  residential: number;
  per_km2: number;
  rural_pct: number;
}

export interface MuniEmploymentData {
  telecom_jobs: number;
  telecom_salary: number;
}

export interface PlanningData {
  plano_diretor: boolean;
  zoning: boolean;
  building_code: boolean;
  digital_governance: boolean;
}

export interface HHITrend {
  direction: 'caindo' | 'subindo' | 'estavel';
  current: number;
  periods: number;
}

export interface QualityProvider {
  name: string;
  score: number;
  speed: number;
  availability: number;
  latency: number;
}

export interface MunicipalityData {
  name: string;
  slug: string;
  code: string;
  population: number;
  households: number;
  subscribers: number;
  isp_count: number;
  penetration: number;
  hhi: number;
  hhi_class: 'competitivo' | 'moderado' | 'concentrado';
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  dsl_pct: number;
  fwa_pct: number;
  quality: { ouro: number; prata: number; bronze: number; sem_selo: number };
  teasers: { tax_debt_isps: number; complaints: number; ouro_isps: number };
  growth_pct: number;
  opportunity: OpportunityScore | Record<string, never>;
  schools: SchoolData | Record<string, never>;
  health: HealthData | Record<string, never>;
  safety: SafetyData | Record<string, never>;
  sanitation: SanitationData | Record<string, never>;
  economy: MuniEconomyData | Record<string, never>;
  density: DensityData | Record<string, never>;
  employment: MuniEmploymentData | Record<string, never>;
  planning: PlanningData | Record<string, never>;
  top_providers: QualityProvider[];
  hhi_trend: HHITrend | Record<string, never>;
  narrative: string;
}

export interface QuarterlyData {
  quarter: string;
  subscribers: number;
  fiber_pct: number;
  isp_count: number;
}

export interface TechSnapshot {
  period: string;
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  dsl_pct: number;
}

export interface ComplaintQuarter {
  quarter: string;
  count: number;
  avg_response_days: number | null;
  avg_satisfaction: number | null;
}

export interface EmploymentYear {
  year: number;
  telecom_jobs: number;
  avg_salary_brl: number | null;
}

export interface EconomyData {
  year: number;
  proxy_pib: number;
}

export interface StateInsights {
  narrative: string;
}

export interface StateAggregates {
  schools_no_internet: number;
  avg_water_pct: number;
  avg_sewage_pct: number;
  digital_governance_count: number;
  top_opportunities: {
    name: string;
    slug: string;
    level: string;
    subscribers: number;
    isp_count: number;
  }[];
}

export interface StateSummary {
  uf: string;
  name: string;
  subscribers: number;
  municipalities: number;
  avg_hhi: number;
  avg_penetration: number;
  fiber_pct: number;
  radio_pct: number;
  cable_pct: number;
  quality: { ouro: number; prata: number; bronze: number; sem_selo: number };
  monopoly_count: number;
  coverage_gap_count: number;
}

export interface NationalData {
  subscribers: number;
  municipalities: number;
  states: StateSummary[];
  period: string;
  generated: string;
}

export interface StateData extends StateSummary {
  cities: MunicipalityData[];
  period: string;
  timeseries: QuarterlyData[];
  tech_evolution: { before?: TechSnapshot; after?: TechSnapshot };
  complaints: ComplaintQuarter[];
  employment: EmploymentYear[];
  economy: EconomyData | Record<string, never>;
  insights: StateInsights;
  aggregates: StateAggregates;
}

// Quality search page data
export interface QualityCityData {
  code: string;
  name: string;
  slug: string;
  providers: {
    name: string;
    seal: string;
    score: number;
    speed: number;
    avail: number;
    latency: number;
  }[];
}

// Import JSON at build time (Next.js static import)
export function getNationalData(): NationalData {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  return require('@/data/market/index.json') as NationalData;
}

export function getStateData(uf: string): StateData | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(`@/data/market/states/${uf.toLowerCase()}.json`) as StateData;
  } catch {
    return null;
  }
}

export function getMunicipalityData(uf: string, slug: string): { state: StateData; city: MunicipalityData } | null {
  const state = getStateData(uf);
  if (!state) return null;
  const city = state.cities.find((c) => c.slug === slug);
  if (!city) return null;
  return { state, city };
}

export function getQualityData(uf: string): QualityCityData[] | null {
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require(`@/data/market/quality/${uf.toLowerCase()}.json`) as QualityCityData[];
  } catch {
    return null;
  }
}

export function getAllStateUFs(): string[] {
  const national = getNationalData();
  return national.states.map((s) => s.uf.toLowerCase());
}

export function getAllMunicipalitySlugs(): { uf: string; slug: string }[] {
  const national = getNationalData();
  const result: { uf: string; slug: string }[] = [];
  for (const st of national.states) {
    const state = getStateData(st.uf);
    if (state) {
      for (const city of state.cities) {
        result.push({ uf: st.uf.toLowerCase(), slug: city.slug });
      }
    }
  }
  return result;
}

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace('.0', '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1).replace('.0', '')}K`;
  return n.toLocaleString('pt-BR');
}

export function formatSubscribers(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1).replace('.0', '')}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return n.toLocaleString('pt-BR');
}

const STATE_NAMES: Record<string, string> = {
  ac: 'Acre', al: 'Alagoas', ap: 'Amapá', am: 'Amazonas',
  ba: 'Bahia', ce: 'Ceará', df: 'Distrito Federal', es: 'Espírito Santo',
  go: 'Goiás', ma: 'Maranhão', mt: 'Mato Grosso', ms: 'Mato Grosso do Sul',
  mg: 'Minas Gerais', pa: 'Pará', pb: 'Paraíba', pr: 'Paraná',
  pe: 'Pernambuco', pi: 'Piauí', rj: 'Rio de Janeiro', rn: 'Rio Grande do Norte',
  rs: 'Rio Grande do Sul', ro: 'Rondônia', rr: 'Roraima', sc: 'Santa Catarina',
  sp: 'São Paulo', se: 'Sergipe', to: 'Tocantins',
};

export function getStateName(uf: string): string {
  return STATE_NAMES[uf.toLowerCase()] || uf.toUpperCase();
}
