# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from python.api.services.proto import rf_service_pb2 as rf__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rf_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RfEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculatePathLoss = channel.unary_unary(
                '/enlace.rf.RfEngine/CalculatePathLoss',
                request_serializer=rf__service__pb2.PathLossRequest.SerializeToString,
                response_deserializer=rf__service__pb2.PathLossResponse.FromString,
                _registered_method=True)
        self.ComputeCoverage = channel.unary_unary(
                '/enlace.rf.RfEngine/ComputeCoverage',
                request_serializer=rf__service__pb2.CoverageRequest.SerializeToString,
                response_deserializer=rf__service__pb2.CoverageResponse.FromString,
                _registered_method=True)
        self.OptimizeTowers = channel.unary_stream(
                '/enlace.rf.RfEngine/OptimizeTowers',
                request_serializer=rf__service__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=rf__service__pb2.OptimizeProgress.FromString,
                _registered_method=True)
        self.LinkBudget = channel.unary_unary(
                '/enlace.rf.RfEngine/LinkBudget',
                request_serializer=rf__service__pb2.LinkBudgetRequest.SerializeToString,
                response_deserializer=rf__service__pb2.LinkBudgetResponse.FromString,
                _registered_method=True)
        self.TerrainProfile = channel.unary_unary(
                '/enlace.rf.RfEngine/TerrainProfile',
                request_serializer=rf__service__pb2.ProfileRequest.SerializeToString,
                response_deserializer=rf__service__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/enlace.rf.RfEngine/Health',
                request_serializer=rf__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=rf__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class RfEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculatePathLoss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeCoverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeTowers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LinkBudget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerrainProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RfEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculatePathLoss': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculatePathLoss,
                    request_deserializer=rf__service__pb2.PathLossRequest.FromString,
                    response_serializer=rf__service__pb2.PathLossResponse.SerializeToString,
            ),
            'ComputeCoverage': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeCoverage,
                    request_deserializer=rf__service__pb2.CoverageRequest.FromString,
                    response_serializer=rf__service__pb2.CoverageResponse.SerializeToString,
            ),
            'OptimizeTowers': grpc.unary_stream_rpc_method_handler(
                    servicer.OptimizeTowers,
                    request_deserializer=rf__service__pb2.OptimizeRequest.FromString,
                    response_serializer=rf__service__pb2.OptimizeProgress.SerializeToString,
            ),
            'LinkBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkBudget,
                    request_deserializer=rf__service__pb2.LinkBudgetRequest.FromString,
                    response_serializer=rf__service__pb2.LinkBudgetResponse.SerializeToString,
            ),
            'TerrainProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.TerrainProfile,
                    request_deserializer=rf__service__pb2.ProfileRequest.FromString,
                    response_serializer=rf__service__pb2.ProfileResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rf__service__pb2.HealthRequest.FromString,
                    response_serializer=rf__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'enlace.rf.RfEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('enlace.rf.RfEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RfEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculatePathLoss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enlace.rf.RfEngine/CalculatePathLoss',
            rf__service__pb2.PathLossRequest.SerializeToString,
            rf__service__pb2.PathLossResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeCoverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enlace.rf.RfEngine/ComputeCoverage',
            rf__service__pb2.CoverageRequest.SerializeToString,
            rf__service__pb2.CoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OptimizeTowers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/enlace.rf.RfEngine/OptimizeTowers',
            rf__service__pb2.OptimizeRequest.SerializeToString,
            rf__service__pb2.OptimizeProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LinkBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enlace.rf.RfEngine/LinkBudget',
            rf__service__pb2.LinkBudgetRequest.SerializeToString,
            rf__service__pb2.LinkBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerrainProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enlace.rf.RfEngine/TerrainProfile',
            rf__service__pb2.ProfileRequest.SerializeToString,
            rf__service__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/enlace.rf.RfEngine/Health',
            rf__service__pb2.HealthRequest.SerializeToString,
            rf__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
