// ── Static example audit data ──
// Representative output from Enlace's internal validation. NOT customer data.
// Shaped to match the real pulso-agent --audit-csv JSON (see audit-types.ts).

import type { AuditResult } from "@/lib/audit-types";

export const exampleAudit: AuditResult = {
  summary: {
    total_onts: 52,
    total_readings: 524160,
    analysis_period_days: 7,
    health_score: 52,
    online: 48,
    offline: 4,
    avg_rx_dbm: -21.4,
    worst_rx_dbm: -30.8,
  },
  faults: [
    {
      fault_id: "FLT-0001",
      fault_type: "fibre cut",
      severity: "critical",
      affected_onts: [
        "ADTN-CF0007",
        "ADTN-CF0008",
        "ADTN-CF0009",
        "ADTN-CF0010",
      ],
      description:
        "Multiple ONTs on PON branch CTP-0/2 dropped simultaneously with no dying gasp — consistent with a fibre cut on the shared branch.",
    },
    {
      fault_id: "FLT-0002",
      fault_type: "power/fibre area event",
      severity: "warning",
      affected_onts: ["ADTN-CF0015", "ADTN-CF0016"],
      description:
        "Mixed dying-gasp and silent drops on CTP-0/4 — likely a localised power event affecting part of the branch.",
    },
  ],
  ghosts: [
    {
      ont_serial: "ADTN-CF0021",
      port: "CTP-0/3",
      rx_power_dbm: -20.1,
      rx_power_variance: 0.2,
      days_online: 41,
      distance_m: 1320,
      estimated_monthly_revenue: 39,
      eth_status: "down",
    },
  ],
  capacity: [],
  flapping: [
    {
      ont_serial: "ADTN-CF0030",
      port: "CTP-0/1",
      flap_count: 18,
      period_hours: 24,
    },
  ],
  weather_correlation: [],
  reflectance: [],
  optical_budget: [],
  sfp_health: [],
  churn_risk: [
    {
      ont_serial: "ADTN-CF0002",
      current_rx_dbm: -27.4,
      days_degrading: 12,
      degradation_rate: -0.18,
      churn_probability_90day: 0.62,
      monthly_revenue_at_risk: 39,
      micro_dropout_count: 7,
      impact: "Signal trending toward failure within ~3 weeks.",
    },
    {
      ont_serial: "ADTN-CF0042",
      current_rx_dbm: -28.9,
      days_degrading: 9,
      degradation_rate: -0.22,
      churn_probability_90day: 0.71,
      monthly_revenue_at_risk: 39,
      micro_dropout_count: 11,
      impact: "Rapid decline — at-risk customer.",
    },
    {
      ont_serial: "ADTN-CF0048",
      current_rx_dbm: -26.8,
      days_degrading: 15,
      degradation_rate: -0.11,
      churn_probability_90day: 0.44,
      monthly_revenue_at_risk: 39,
      micro_dropout_count: 4,
      impact: "Slow degradation — monitor.",
    },
  ],
  tickets: [],
  diagnostics: {
    olt_id: "OLT-VALIDATION-01",
    overall_health: "needs_attention",
    timestamp: "2026-06-10T09:00:00Z",
    alerts: [],
    capacity_warnings: [],
    summary: {
      total_onts: 52,
      online: 48,
      offline: 4,
      offline_rate_percent: 7.7,
      avg_rx_power_dbm: -21.4,
      worst_rx_power_dbm: -30.8,
      critical_signal: 2,
      low_signal: 3,
    },
  },
  impact: {
    fault_id: "FLT-0001",
    affected_onts: 4,
    active_onts: 48,
    impact_score: 72,
    priority: "high",
    time_sensitivity: "immediate",
  },
  // A small representative ONT table.
  onts: [
    {
      ont_index: 1,
      serial_number: "ADTN-CF0001",
      pon_port: "CTP-0/1",
      status: "online",
      rx_power_dbm: -17.2,
      tx_power_dbm: 2.1,
      distance_meters: 840,
      uptime_seconds: 3542400,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: 1000,
      last_down_cause: null,
      in_octets: 84200000000,
      out_octets: 12100000000,
      extended: null,
    },
    {
      ont_index: 2,
      serial_number: "ADTN-CF0002",
      pon_port: "CTP-0/1",
      status: "online",
      rx_power_dbm: -27.4,
      tx_power_dbm: 2.4,
      distance_meters: 2980,
      uptime_seconds: 1036800,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: 1000,
      last_down_cause: null,
      in_octets: 21000000000,
      out_octets: 3400000000,
      extended: null,
    },
    {
      ont_index: 7,
      serial_number: "ADTN-CF0007",
      pon_port: "CTP-0/2",
      status: "offline",
      rx_power_dbm: null,
      tx_power_dbm: null,
      distance_meters: 1610,
      uptime_seconds: 0,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: null,
      last_down_cause: "los",
      in_octets: null,
      out_octets: null,
      extended: null,
    },
    {
      ont_index: 21,
      serial_number: "ADTN-CF0021",
      pon_port: "CTP-0/3",
      status: "online",
      rx_power_dbm: -20.1,
      tx_power_dbm: 2.0,
      distance_meters: 1320,
      uptime_seconds: 3542400,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: 1000,
      last_down_cause: null,
      in_octets: 1200000,
      out_octets: 410000,
      extended: null,
    },
    {
      ont_index: 30,
      serial_number: "ADTN-CF0030",
      pon_port: "CTP-0/1",
      status: "online",
      rx_power_dbm: -22.6,
      tx_power_dbm: 2.2,
      distance_meters: 2110,
      uptime_seconds: 86400,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: 1000,
      last_down_cause: "los",
      in_octets: 44000000000,
      out_octets: 7700000000,
      extended: null,
    },
    {
      ont_index: 42,
      serial_number: "ADTN-CF0042",
      pon_port: "CTP-0/4",
      status: "online",
      rx_power_dbm: -28.9,
      tx_power_dbm: 2.6,
      distance_meters: 3340,
      uptime_seconds: 777600,
      equipment_id: "SDX-6320",
      firmware_version: "R6.3.0",
      vendor_id: "adtran",
      eth_speed_mbps: 1000,
      last_down_cause: null,
      in_octets: 9800000000,
      out_octets: 1600000000,
      extended: null,
    },
  ],
};
